# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sign_num <- function(x) {
    .Call(`_TimeVarying_sign_num`, x)
}

dloglik_likelihood_stratify <- function(knot, facility, delta, z, b_spline, theta) {
    .Call(`_TimeVarying_dloglik_likelihood_stratify`, knot, facility, delta, z, b_spline, theta)
}

ddloglik_gradient <- function(knot, facility, z, delta, b_spline, theta, number_facility = 1L) {
    .Call(`_TimeVarying_ddloglik_gradient`, knot, facility, z, delta, b_spline, theta, number_facility)
}

GDboost_gradient <- function(knot, rate, facility, delta, z, b_spline, theta) {
    .Call(`_TimeVarying_GDboost_gradient`, knot, rate, facility, delta, z, b_spline, theta)
}

dloglik_likelihood_gradient <- function(knot, facility, delta, z, b_spline, theta) {
    .Call(`_TimeVarying_dloglik_likelihood_gradient`, knot, facility, delta, z, b_spline, theta)
}

ddloglik <- function(knot, facility, delta, z, b_spline, theta, number_facility) {
    .Call(`_TimeVarying_ddloglik`, knot, facility, delta, z, b_spline, theta, number_facility)
}

NRloop <- function(knot, facility, delta, z, b_spline, theta, M_stop, number_facility, rate, tol) {
    .Call(`_TimeVarying_NRloop`, knot, facility, delta, z, b_spline, theta, M_stop, number_facility, rate, tol)
}

